sudo: required
services: 
  - docker
before_install:
  - docker build -t atabekcyber/react-test -f ./client/Dockerfile.dev
script:
  - docker run atabekcyber/react-test npm test -- --coverage

after_success:
  - docker build -t atabekcyber/multi-client ./client
  - docker build -t atabekcyber/multi-nginx ./ngnix
  - docker build -t atabekcyber/multi-server ./server
  - docker build -t atabekcyber/multi-worker ./worker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password--stdin
  - docker push atabekcyber/multi-client
  - docker push atabekcyber/multi-ngnix
  - docker push atabekcyber/multi-worker
  - docker push atabekcyber/multi-server