sudo: required
services: 
  - docker
before_install:
  - docker build -t atabekcyber/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true atabekcyber/react-test npm test


after_success:
  - docker build -t atabekcyber/multi-client ./client
  - docker build -t atabekcyber/multi-nginx ./nginx
  - docker build -t atabekcyber/multi-server ./server
  - docker build -t atabekcyber/multi-worker ./worker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push atabekcyber/multi-client
  - docker push atabekcyber/multi-nginx
  - docker push atabekcyber/multi-worker
  - docker push atabekcyber/multi-server

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-west-1-257894499063'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY